import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { 
  Megaphone, ArrowLeft, Calendar, Sparkles, Send, IndianRupee, Award, Percent, 
  BarChart2, ShieldCheck, CheckSquare, Clock, ArrowRight, MessageSquare 
} from 'lucide-react';
import api from '../lib/api';
import Explainability from '../components/Explainability';
import PostCampaignReview from '../components/PostCampaignReview';

export default function CampaignDetail() {
  const { id } = useParams();
  const navigate = useNavigate();
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);

  const fetchCampaignDetail = async () => {
    try {
      const res = await api.get(`/campaigns/${id}`);
      setData(res.data);
    } catch (err) {
      console.error('Failed to load campaign details:', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchCampaignDetail();
    const interval = setInterval(fetchCampaignDetail, 2500);
    return () => clearInterval(interval);
  }, [id]);

  if (loading) {
    return <div className="loading-spinner"><div className="spinner" /></div>;
  }

  if (!data || !data.campaign) {
    return (
      <div className="empty-state">
        <p>Campaign not found.</p>
        <button onClick={() => navigate('/campaigns')} className="btn btn-secondary btn-sm" style={{ marginTop: '10px' }}>
          Back to Campaigns
        </button>
      </div>
    );
  }

  const { campaign, communications = [] } = data;

  const totalSent = campaign.total_sent || 0;
  const totalDelivered = campaign.total_delivered || 0;
  const totalOpened = campaign.total_opened || 0;
  const totalClicked = campaign.total_clicked || 0;
  const totalConverted = campaign.total_converted || 0;
  const revenue = campaign.revenue_generated || 0;

  const estCost = totalSent * 1.5;
  const roi = revenue > 0 ? (revenue / estCost).toFixed(1) : '0.0';

  const deliveryRate = totalSent > 0 ? Math.round((totalDelivered / totalSent) * 100) : 0;
  const openRate = totalDelivered > 0 ? Math.round((totalOpened / totalDelivered) * 100) : 0;
  const clickRate = totalOpened > 0 ? Math.round((totalClicked / totalOpened) * 100) : 0;
  const conversionRate = totalClicked > 0 ? Math.round((totalConverted / totalClicked) * 100) : 0;

  const formatCurrency = (val) => `₹${parseFloat(val || 0).toLocaleString('en-IN')}`;

  const formatDate = (dateStr) => {
    if (!dateStr) return '—';
    return new Date(dateStr).toLocaleString('en-IN', {
      day: 'numeric',
      month: 'short',
      hour: '2-digit',
      minute: '2-digit'
    });
  };

  const getStatusBadge = (status) => {
    const map = {
      completed: 'badge-success',
      sending: 'badge-info',
      draft: 'badge-neutral',
      failed: 'badge-error'
    };
    return map[status] || 'badge-neutral';
  };

  const getCommStatusBadge = (status) => {
    const map = {
      delivered: 'badge-success',
      opened: 'badge-info',
      read: 'badge-info',
      clicked: 'badge-success',
      converted: 'badge-success',
      failed: 'badge-error',
      sent: 'badge-neutral',
      queued: 'badge-neutral'
    };
    return map[status] || 'badge-neutral';
  };

  // Timeline events definition
  const timelineEvents = [
    { name: "Created", done: true, time: campaign.created_at },
    { name: "Generated by AI", done: true, time: campaign.created_at },
    { name: "Approved", done: true, time: campaign.created_at },
    { name: "Sent", done: campaign.status !== 'draft', time: campaign.sent_at },
    { name: "Delivered", done: totalDelivered > 0, time: campaign.sent_at },
    { name: "Opened", done: totalOpened > 0, time: communications.find(c => c.opened_at)?.opened_at },
    { name: "Clicked", done: totalClicked > 0, time: communications.find(c => c.clicked_at)?.clicked_at },
    { name: "Converted", done: totalConverted > 0, time: communications.find(c => c.converted_at)?.converted_at }
  ];

  return (
    <div>
      <div style={{ marginBottom: '16px', display: 'flex', alignItems: 'center', gap: '8px' }}>
        <button onClick={() => navigate('/campaigns')} className="btn btn-ghost btn-sm" style={{ padding: '6px' }}>
          <ArrowLeft size={16} />
        </button>
        <span style={{ fontSize: '0.85rem', color: 'var(--text-secondary)' }}>Back to Campaigns</span>
      </div>

      <div className="page-header" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
        <div>
          <h2 style={{ display: 'flex', alignItems: 'center', gap: '8px', margin: 0 }}>
            <Megaphone size={22} style={{ color: '#6366f1' }} /> {campaign.name}
          </h2>
          <div style={{ display: 'flex', gap: '8px', alignItems: 'center', marginTop: '6px' }}>
            <span className={`channel-tag channel-${campaign.channel?.toLowerCase()}`}>{campaign.channel}</span>
            <span className={`badge ${getStatusBadge(campaign.status)}`}>{campaign.status}</span>
            {campaign.confidence_rate && (
              <span style={{ fontSize: '0.8rem', fontWeight: 600, color: 'var(--text-primary)', display: 'inline-flex', alignItems: 'center', gap: '3px' }}>
                <Sparkles size={12} style={{ color: '#6366f1' }} /> {campaign.confidence_rate}% Confidence
              </span>
            )}
            <span style={{ fontSize: '0.8rem', color: 'var(--text-tertiary)' }}>Created {formatDate(campaign.created_at)}</span>
          </div>
        </div>
      </div>

      {/* Overview Statistics Grid */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(140px, 1fr))', gap: '12px', marginBottom: '24px' }}>
        <div style={{ border: '1px solid var(--border-primary)', padding: '12px', borderRadius: 'var(--radius-md)', background: 'var(--bg-card)' }}>
          <div style={{ fontSize: '0.65rem', color: 'var(--text-tertiary)', textTransform: 'uppercase', fontWeight: 600 }}>Total Revenue</div>
          <div style={{ fontSize: '1.25rem', fontWeight: 700, color: 'var(--success)', marginTop: '2px', display: 'flex', alignItems: 'center', gap: '2px' }}>
            <IndianRupee size={16} /> {parseFloat(campaign.revenue_generated || 0).toLocaleString('en-IN')}
          </div>
        </div>
        <div style={{ border: '1px solid var(--border-primary)', padding: '12px', borderRadius: 'var(--radius-md)', background: 'var(--bg-card)' }}>
          <div style={{ fontSize: '0.65rem', color: 'var(--text-tertiary)', textTransform: 'uppercase', fontWeight: 600 }}>ROI MULTIPLIER</div>
          <div style={{ fontSize: '1.25rem', fontWeight: 700, color: 'var(--text-primary)', marginTop: '2px', display: 'flex', alignItems: 'center', gap: '2px' }}>
            <Award size={16} /> {roi}x
          </div>
        </div>
        <div style={{ border: '1px solid var(--border-primary)', padding: '12px', borderRadius: 'var(--radius-md)', background: 'var(--bg-card)' }}>
          <div style={{ fontSize: '0.65rem', color: 'var(--text-tertiary)', textTransform: 'uppercase', fontWeight: 600 }}>DELIVERY RATE</div>
          <div style={{ fontSize: '1.25rem', fontWeight: 700, color: 'var(--text-primary)', marginTop: '2px', display: 'flex', alignItems: 'center', gap: '2px' }}>
            <Percent size={14} /> {deliveryRate}%
          </div>
        </div>
        <div style={{ border: '1px solid var(--border-primary)', padding: '12px', borderRadius: 'var(--radius-md)', background: 'var(--bg-card)' }}>
          <div style={{ fontSize: '0.65rem', color: 'var(--text-tertiary)', textTransform: 'uppercase', fontWeight: 600 }}>CTR (CLICK-THROUGH)</div>
          <div style={{ fontSize: '1.25rem', fontWeight: 700, color: 'var(--text-primary)', marginTop: '2px', display: 'flex', alignItems: 'center', gap: '2px' }}>
            <Percent size={14} /> {clickRate}%
          </div>
        </div>
        <div style={{ border: '1px solid var(--border-primary)', padding: '12px', borderRadius: 'var(--radius-md)', background: 'var(--bg-card)' }}>
          <div style={{ fontSize: '0.65rem', color: 'var(--text-tertiary)', textTransform: 'uppercase', fontWeight: 600 }}>CONVERSION RATE</div>
          <div style={{ fontSize: '1.25rem', fontWeight: 700, color: 'var(--text-primary)', marginTop: '2px', display: 'flex', alignItems: 'center', gap: '2px' }}>
            <Percent size={14} /> {conversionRate}%
          </div>
        </div>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '2fr 1fr', gap: '20px', alignItems: 'flex-start', marginBottom: '24px' }}>
        {/* Left Column: Funnel and Message */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>
          
          {/* Conversion Funnel */}
          <div className="card" style={{ padding: '16px' }}>
            <div style={{ fontSize: '0.8rem', fontWeight: 600, color: 'var(--text-secondary)', marginBottom: '12px', textTransform: 'uppercase', letterSpacing: '0.04em', display: 'flex', alignItems: 'center', gap: '6px' }}>
              <BarChart2 size={14} /> Performance Conversion Funnel
            </div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
              {/* Sent */}
              <div>
                <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.78rem', marginBottom: '3px' }}>
                  <span style={{ fontWeight: 600 }}>1. Sent to Gateway</span>
                  <span>{totalSent} users (100%)</span>
                </div>
                <div style={{ width: '100%', height: '12px', background: 'var(--border-secondary)', borderRadius: '6px', overflow: 'hidden' }}>
                  <div style={{ width: '100%', height: '100%', background: 'var(--text-primary)', borderRadius: '6px' }} />
                </div>
              </div>
              {/* Delivered */}
              <div>
                <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.78rem', marginBottom: '3px' }}>
                  <span style={{ fontWeight: 600 }}>2. Delivered to Device</span>
                  <span>{totalDelivered} users ({deliveryRate}%)</span>
                </div>
                <div style={{ width: '100%', height: '12px', background: 'var(--border-secondary)', borderRadius: '6px', overflow: 'hidden' }}>
                  <div style={{ width: `${deliveryRate}%`, height: '100%', background: 'var(--text-secondary)', borderRadius: '6px' }} />
                </div>
              </div>
              {/* Opened */}
              <div>
                <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.78rem', marginBottom: '3px' }}>
                  <span style={{ fontWeight: 600 }}>3. Opened & Read</span>
                  <span>{totalOpened} users ({openRate}% of delivered)</span>
                </div>
                <div style={{ width: '100%', height: '12px', background: 'var(--border-secondary)', borderRadius: '6px', overflow: 'hidden' }}>
                  <div style={{ width: `${Math.round((totalOpened / (totalSent || 1)) * 100)}%`, height: '100%', background: 'var(--border-focus)', borderRadius: '6px' }} />
                </div>
              </div>
              {/* Clicked */}
              <div>
                <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.78rem', marginBottom: '3px' }}>
                  <span style={{ fontWeight: 600 }}>4. Clicked Call-to-Action</span>
                  <span>{totalClicked} users ({clickRate}% of opened)</span>
                </div>
                <div style={{ width: '100%', height: '12px', background: 'var(--border-secondary)', borderRadius: '6px', overflow: 'hidden' }}>
                  <div style={{ width: `${Math.round((totalClicked / (totalSent || 1)) * 100)}%`, height: '100%', background: '#6366f1', borderRadius: '6px' }} />
                </div>
              </div>
              {/* Converted */}
              <div>
                <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.78rem', marginBottom: '3px' }}>
                  <span style={{ fontWeight: 600, color: 'var(--success)' }}>5. Converted & Paid</span>
                  <span style={{ fontWeight: 600, color: 'var(--success)' }}>{totalConverted} sales ({conversionRate}% of clicked)</span>
                </div>
                <div style={{ width: '100%', height: '12px', background: 'var(--border-secondary)', borderRadius: '6px', overflow: 'hidden' }}>
                  <div style={{ width: `${Math.round((totalConverted / (totalSent || 1)) * 100)}%`, height: '100%', background: 'var(--success)', borderRadius: '6px' }} />
                </div>
              </div>
            </div>
          </div>

          {/* Generated Message Copy template */}
          <div className="card" style={{ padding: '16px' }}>
            <div style={{ fontSize: '0.8rem', fontWeight: 600, color: 'var(--text-secondary)', marginBottom: '10px', textTransform: 'uppercase', display: 'flex', alignItems: 'center', gap: '6px' }}>
              <MessageSquare size={14} /> AI Dispatched Message Copy
            </div>
            {campaign.subject && (
              <div style={{ marginBottom: '8px', fontSize: '0.82rem' }}>
                <span style={{ color: 'var(--text-tertiary)' }}>Subject Line:</span> <strong style={{ color: 'var(--text-primary)' }}>{campaign.subject}</strong>
              </div>
            )}
            <div style={{ padding: '12px', background: 'var(--bg-secondary)', border: '1px solid var(--border-primary)', borderRadius: 'var(--radius-md)', fontSize: '0.85rem', whiteSpace: 'pre-wrap', lineHeight: 1.6, fontFamily: 'monospace' }}>
              {campaign.message_template}
            </div>
          </div>

        </div>

        {/* Right Column: Audience metadata & timeline */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>
          
          {/* Audience & Target Segment */}
          <div className="card" style={{ padding: '16px' }}>
            <div style={{ fontSize: '0.8rem', fontWeight: 600, color: 'var(--text-secondary)', marginBottom: '8px', textTransform: 'uppercase' }}>Audience segment</div>
            <h4 style={{ fontSize: '1rem', fontWeight: 700, margin: '0 0 4px 0' }}>{campaign.segment_name || 'All Customers'}</h4>
            <div style={{ fontSize: '0.78rem', color: 'var(--text-secondary)' }}>Target size: {totalSent} customers matched</div>
          </div>

          {/* Journey Timeline */}
          <div className="card" style={{ padding: '16px' }}>
            <div style={{ fontSize: '0.8rem', fontWeight: 600, color: 'var(--text-secondary)', marginBottom: '12px', textTransform: 'uppercase' }}>Campaign Journey Timeline</div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '12px', position: 'relative', paddingLeft: '20px' }}>
              {/* Vertical line indicator */}
              <div style={{ position: 'absolute', left: '4px', top: '4px', bottom: '4px', width: '2px', background: 'var(--border-primary)' }} />
              
              {timelineEvents.map((evt, idx) => (
                <div key={idx} style={{ position: 'relative', display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', fontSize: '0.78rem' }}>
                  {/* Circle dot indicator */}
                  <div style={{ 
                    position: 'absolute', 
                    left: '-20px', 
                    top: '3px', 
                    width: '10px', 
                    height: '10px', 
                    borderRadius: '50%', 
                    background: evt.done ? 'var(--success)' : 'var(--border-primary)',
                    border: evt.done ? 'none' : '1px solid var(--border-secondary)'
                  }} />
                  <span style={{ fontWeight: evt.done ? 600 : 'normal', color: evt.done ? 'var(--text-primary)' : 'var(--text-tertiary)' }}>{evt.name}</span>
                  <span style={{ color: 'var(--text-secondary)', fontSize: '0.72rem' }}>{evt.time ? new Date(evt.time).toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' }) : '—'}</span>
                </div>
              ))}
            </div>
          </div>

        </div>
      </div>

      {/* Real-time Delivery & Telemetry Logs */}
      {communications.length > 0 && (
        <div className="card" style={{ padding: '16px', marginBottom: '24px', border: '1px solid var(--border-primary)' }}>
          <div style={{ fontSize: '0.8rem', fontWeight: 600, color: 'var(--text-secondary)', marginBottom: '12px', textTransform: 'uppercase', letterSpacing: '0.04em' }}>
            Real-time Delivery & Telemetry Logs
          </div>
          <div className="table-container" style={{ maxHeight: '350px', overflowY: 'auto' }}>
            <table className="table" style={{ fontSize: '0.82rem' }}>
              <thead>
                <tr>
                  <th>Recipient</th>
                  <th>Status</th>
                  <th>Sent</th>
                  <th>Delivered</th>
                  <th>Opened / Read</th>
                  <th>Clicked / Converted</th>
                  <th>Feedback / Revenue</th>
                </tr>
              </thead>
              <tbody>
                {communications.map(c => (
                  <tr key={c.id}>
                    <td>
                      <div style={{ fontWeight: 600 }}>{c.customer_name}</div>
                      <div style={{ fontSize: '0.72rem', color: 'var(--text-secondary)' }}>{c.customer_email}</div>
                    </td>
                    <td>
                      <span className={`badge ${getCommStatusBadge(c.status)}`}>
                        {c.status}
                      </span>
                    </td>
                    <td style={{ color: 'var(--text-secondary)' }}>{c.sent_at ? formatDate(c.sent_at) : '—'}</td>
                    <td style={{ color: 'var(--text-secondary)' }}>{c.delivered_at ? formatDate(c.delivered_at) : '—'}</td>
                    <td style={{ color: 'var(--text-secondary)' }}>
                      {c.opened_at ? (
                        <div>
                          <div>Opened: {formatDate(c.opened_at)}</div>
                          {c.read_at && <div style={{ fontSize: '0.72rem', color: 'var(--success)', marginTop: '2px' }}>Read: {formatDate(c.read_at)}</div>}
                        </div>
                      ) : '—'}
                    </td>
                    <td style={{ color: 'var(--text-secondary)' }}>
                      {c.clicked_at ? (
                        <div>
                          <div>Clicked: {formatDate(c.clicked_at)}</div>
                          {c.converted_at && <div style={{ fontSize: '0.72rem', color: 'var(--success)', marginTop: '2px' }}>Converted: {formatDate(c.converted_at)}</div>}
                        </div>
                      ) : '—'}
                    </td>
                    <td>
                      {c.status === 'failed' && (
                        <span style={{ color: 'var(--error)', fontSize: '0.78rem', fontWeight: 500 }}>
                          {c.error_message || 'Delivery failed'}
                        </span>
                      )}
                      {c.conversion_revenue ? (
                        <span style={{ fontWeight: 600, color: 'var(--success)' }}>
                          {formatCurrency(c.conversion_revenue)}
                        </span>
                      ) : (
                        c.status !== 'failed' ? '—' : null
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* Explainability component */}
      <Explainability 
        audienceReason="Selected because LTV and purchase history match the targeting criteria for retention win-backs."
        channelReason={`${campaign.channel} was recommended due to its strong delivery probability for the matched cohort profiles.`}
        offerReason="Cashback discount incentive selected to secure repeating conversion outcomes without excessive profit erosion."
        timingReason="Dispatched during active shopping periods resolved from previous transaction telemetry log patterns."
        predictionReason={`AI Forecast matches observed conversion parameters for ${campaign.channel} templates.`}
      />

      {/* Post Campaign AI Review analyst panel */}
      {campaign.status === 'completed' && (
        <PostCampaignReview campaign={campaign} />
      )}
    </div>
  );
}
